export { ReactComponent as Behance } from './behance.svg'
export { ReactComponent as Github } from './github.svg'
export { ReactComponent as Linkedin } from './linkedin.svg'
export { ReactComponent as Location } from './location.svg'
export { ReactComponent as Mail } from './mail.svg'
export { ReactComponent as Name } from './name.svg'
export { ReactComponent as Skype } from './skype.svg'
