declare module 'grommet-icons' {
  export const Accessibility: any
  export const Achievement: any
  export const Action: any
  export const Actions: any
  export const Ad: any
  export const Add: any
  export const AddCircle: any
  export const Aed: any
  export const Aggregate: any
  export const Aid: any
  export const AidOption: any
  export const Alarm: any
  export const Alert: any
  export const Amazon: any
  export const Amex: any
  export const Analytics: any
  export const Anchor: any
  export const Android: any
  export const Announce: any
  export const Apple: any
  export const Apps: any
  export const Archive: any
  export const Archlinux: any
  export const Article: any
  export const Aruba: any
  export const Ascend: any
  export const AssistListening: any
  export const Atm: any
  export const Attachment: any
  export const Attraction: any
  export const Baby: any
  export const BackTen: any
  export const Bar: any
  export const BarChart: any
  export const Basket: any
  export const Bike: any
  export const Bitcoin: any
  export const Blank: any
  export const BlockQuote: any
  export const Blog: any
  export const Bluetooth: any
  export const Bold: any
  export const Book: any
  export const Bookmark: any
  export const BottomCorner: any
  export const Braille: any
  export const Briefcase: any
  export const Brush: any
  export const Bug: any
  export const Bundle: any
  export const Bus: any
  export const BusinessService: any
  export const Cafeteria: any
  export const Calculator: any
  export const Calendar: any
  export const Camera: any
  export const Capacity: any
  export const Car: any
  export const CaretDown: any
  export const CaretNext: any
  export const CaretPrevious: any
  export const CaretUp: any
  export const Cart: any
  export const Catalog: any
  export const CatalogOption: any
  export const Centos: any
  export const Channel: any
  export const ChapterAdd: any
  export const ChapterNext: any
  export const ChapterPrevious: any
  export const Chat: any
  export const ChatOption: any
  export const Checkbox: any
  export const CheckboxSelected: any
  export const Checkmark: any
  export const Chrome: any
  export const CircleInformation: any
  export const CirclePlay: any
  export const CircleQuestion: any
  export const Clear: any
  export const ClearOption: any
  export const Cli: any
  export const Clipboard: any
  export const Clock: any
  export const Clone: any
  export const Close: any
  export const ClosedCaption: any
  export const Cloud: any
  export const CloudComputer: any
  export const CloudDownload: any
  export const CloudSoftware: any
  export const CloudUpload: any
  export const Cloudlinux: any
  export const Cluster: any
  export const CoatCheck: any
  export const Code: any
  export const CodeSandbox: any
  export const Codepen: any
  export const Columns: any
  export const Command: any
  export const Compare: any
  export const Compass: any
  export const Compliance: any
  export const Configure: any
  export const Connect: any
  export const Connectivity: any
  export const Contact: any
  export const ContactInfo: any
  export const Contract: any
  export const Copy: any
  export const CreativeCommons: any
  export const CreditCard: any
  export const Css3: any
  export const Cube: any
  export const Cubes: any
  export const Currency: any
  export const Cursor: any
  export const Cut: any
  export const Cycle: any
  export const Dashboard: any
  export const Database: any
  export const Debian: any
  export const Deliver: any
  export const Deploy: any
  export const Descend: any
  export const Desktop: any
  export const Detach: any
  export const Device: any
  export const Diamond: any
  export const Directions: any
  export const Disc: any
  export const Dislike: any
  export const Docker: any
  export const Document: any
  export const DocumentCloud: any
  export const DocumentConfig: any
  export const DocumentCsv: any
  export const DocumentDownload: any
  export const DocumentExcel: any
  export const DocumentImage: any
  export const DocumentLocked: any
  export const DocumentMissing: any
  export const DocumentNotes: any
  export const DocumentOutlook: any
  export const DocumentPdf: any
  export const DocumentPerformance: any
  export const DocumentPpt: any
  export const DocumentRtf: any
  export const DocumentSound: any
  export const DocumentStore: any
  export const DocumentTest: any
  export const DocumentText: any
  export const DocumentThreat: any
  export const DocumentTime: any
  export const DocumentTransfer: any
  export const DocumentTxt: any
  export const DocumentUpdate: any
  export const DocumentUpload: any
  export const DocumentUser: any
  export const DocumentVerified: any
  export const DocumentVideo: any
  export const DocumentWindows: any
  export const DocumentWord: any
  export const DocumentZip: any
  export const Domain: any
  export const Dos: any
  export const Down: any
  export const Download: any
  export const Drag: any
  export const Drawer: any
  export const DriveCage: any
  export const Dropbox: any
  export const Duplicate: any
  export const Dxc: any
  export const Edge: any
  export const Edit: any
  export const Eject: any
  export const Elevator: any
  export const Emergency: any
  export const Emoji: any
  export const EmptyCircle: any
  export const Erase: any
  export const Escalator: any
  export const Expand: any
  export const Facebook: any
  export const FacebookOption: any
  export const Fan: any
  export const FastForward: any
  export const Favorite: any
  export const Fedora: any
  export const Filter: any
  export const FingerPrint: any
  export const Fireball: any
  export const Firefox: any
  export const Flag: any
  export const FlagFill: any
  export const Folder: any
  export const FolderCycle: any
  export const FolderOpen: any
  export const FormAdd: any
  export const FormAttachment: any
  export const FormCalendar: any
  export const FormCheckmark: any
  export const FormClock: any
  export const FormClose: any
  export const FormCut: any
  export const FormDown: any
  export const FormEdit: any
  export const FormFilter: any
  export const FormFolder: any
  export const FormLocation: any
  export const FormLock: any
  export const FormNext: any
  export const FormNextLink: any
  export const FormPrevious: any
  export const FormPreviousLink: any
  export const FormRefresh: any
  export const FormSchedule: any
  export const FormSearch: any
  export const FormSubtract: any
  export const FormTrash: any
  export const FormUp: any
  export const FormUpload: any
  export const FormView: any
  export const FormViewHide: any
  export const ForwardTen: any
  export const Freebsd: any
  export const Gallery: any
  export const Gamepad: any
  export const Gift: any
  export const Github: any
  export const Globe: any
  export const Golang: any
  export const Google: any
  export const GooglePlus: any
  export const GoogleWallet: any
  export const Gremlin: any
  export const Grid: any
  export const Grommet: any
  export const Group: any
  export const Grow: any
  export const Hadoop: any
  export const Halt: any
  export const Help: any
  export const Heroku: any
  export const History: any
  export const Home: any
  export const Horton: any
  export const Host: any
  export const HostMaintenance: any
  export const Hp: any
  export const Hpe: any
  export const HpeLabs: any
  export const Hpi: any
  export const Html5: any
  export const IceCream: any
  export const Image: any
  export const Impact: any
  export const InProgress: any
  export const Inbox: any
  export const Indicator: any
  export const Info: any
  export const Inherit: any
  export const Inspect: any
  export const Instagram: any
  export const Install: any
  export const InstallOption: any
  export const Integration: any
  export const InternetExplorer: any
  export const Italic: any
  export const Iteration: any
  export const Java: any
  export const Keyboard: any
  export const Language: any
  export const Launch: any
  export const Layer: any
  export const License: any
  export const Like: any
  export const LineChart: any
  export const Link: any
  export const LinkBottom: any
  export const LinkDown: any
  export const LinkNext: any
  export const LinkPrevious: any
  export const LinkTop: any
  export const LinkUp: any
  export const Linkedin: any
  export const LinkedinOption: any
  export const Local: any
  export const Location: any
  export const LocationPin: any
  export const Lock: any
  export const Login: any
  export const Logout: any
  export const Lounge: any
  export const Magic: any
  export const Mail: any
  export const MailOption: any
  export const Mandriva: any
  export const Manual: any
  export const Map: any
  export const MapLocation: any
  export const Mastercard: any
  export const Medium: any
  export const Menu: any
  export const Microfocus: any
  export const Microphone: any
  export const Money: any
  export const Monitor: any
  export const Monospace: any
  export const More: any
  export const Multimedia: any
  export const Multiple: any
  export const Music: any
  export const Mysql: any
  export const Navigate: any
  export const Network: any
  export const New: any
  export const NewWindow: any
  export const Next: any
  export const Nodes: any
  export const Norton: any
  export const Note: any
  export const Notes: any
  export const Notification: any
  export const ObjectGroup: any
  export const ObjectUngroup: any
  export const OfflineStorage: any
  export const Onedrive: any
  export const Opera: any
  export const Optimize: any
  export const Oracle: any
  export const OrderedList: any
  export const Organization: any
  export const Overview: any
  export const Paint: any
  export const Pan: any
  export const Pause: any
  export const PauseFill: any
  export const Paypal: any
  export const Performance: any
  export const PersonalComputer: any
  export const PieChart: any
  export const PiedPiper: any
  export const Pin: any
  export const Pinterest: any
  export const Plan: any
  export const Play: any
  export const PlayFill: any
  export const Power: any
  export const PowerCycle: any
  export const PowerForceShutdown: any
  export const PowerReset: any
  export const PowerShutdown: any
  export const Previous: any
  export const Print: any
  export const ProductHunt: any
  export const Projects: any
  export const Radial: any
  export const RadialSelected: any
  export const Raspberry: any
  export const Reactjs: any
  export const Reddit: any
  export const Redhat: any
  export const Redo: any
  export const Refresh: any
  export const Resources: any
  export const Restaurant: any
  export const Restroom: any
  export const RestroomMen: any
  export const RestroomWomen: any
  export const Resume: any
  export const Return: any
  export const Revert: any
  export const Rewind: any
  export const Risk: any
  export const Robot: any
  export const RotateLeft: any
  export const RotateRight: any
  export const Rss: any
  export const Run: any
  export const SafariOption: any
  export const Satellite: any
  export const Save: any
  export const Scan: any
  export const Schedule: any
  export const ScheduleNew: any
  export const SchedulePlay: any
  export const Schedules: any
  export const Sco: any
  export const Scorecard: any
  export const Search: any
  export const SearchAdvanced: any
  export const Secure: any
  export const Select: any
  export const Selection: any
  export const Semantics: any
  export const Send: any
  export const Server: any
  export const ServerCluster: any
  export const Servers: any
  export const ServicePlay: any
  export const Services: any
  export const SettingsOption: any
  export const Share: any
  export const ShareOption: any
  export const Shield: any
  export const ShieldSecurity: any
  export const Shift: any
  export const Shop: any
  export const Sidebar: any
  export const Sign: any
  export const Skype: any
  export const Slack: any
  export const Snapchat: any
  export const Solaris: any
  export const Sort: any
  export const Spa: any
  export const Split: any
  export const Splits: any
  export const Square: any
  export const StackOverflow: any
  export const Stakeholder: any
  export const Star: any
  export const StarHalf: any
  export const StatusCritical: any
  export const StatusCriticalSmall: any
  export const StatusDisabled: any
  export const StatusDisabledSmall: any
  export const StatusGood: any
  export const StatusGoodSmall: any
  export const StatusInfo: any
  export const StatusInfoSmall: any
  export const StatusPlaceholder: any
  export const StatusPlaceholderSmall: any
  export const StatusUnknown: any
  export const StatusUnknownSmall: any
  export const StatusWarning: any
  export const StatusWarningSmall: any
  export const Steps: any
  export const StepsOption: any
  export const Stop: any
  export const StopFill: any
  export const Storage: any
  export const StreetView: any
  export const StrikeThrough: any
  export const Stripe: any
  export const Subscript: any
  export const Subtract: any
  export const SubtractCircle: any
  export const Superscript: any
  export const Support: any
  export const Suse: any
  export const Swift: any
  export const Swim: any
  export const Sync: any
  export const System: any
  export const Table: any
  export const TableAdd: any
  export const Tag: any
  export const Tape: any
  export const TapeOption: any
  export const Target: any
  export const Task: any
  export const Tasks: any
  export const Technology: any
  export const Template: any
  export const Terminal: any
  export const Test: any
  export const TestDesktop: any
  export const TextAlignCenter: any
  export const TextAlignFull: any
  export const TextAlignLeft: any
  export const TextAlignRight: any
  export const TextWrap: any
  export const Threats: any
  export const ThreeD: any
  export const ThreeDffects: any
  export const Ticket: any
  export const Tip: any
  export const Toast: any
  export const Tools: any
  export const Tooltip: any
  export const TopCorner: any
  export const Train: any
  export const Transaction: any
  export const Trash: any
  export const Tree: any
  export const TreeOption: any
  export const Trigger: any
  export const Trophy: any
  export const Troubleshoot: any
  export const Tty: any
  export const Tumblr: any
  export const Turbolinux: any
  export const Twitter: any
  export const Ubuntu: any
  export const Underline: any
  export const Undo: any
  export const Unlink: any
  export const Unlock: any
  export const UnorderedList: any
  export const Up: any
  export const Update: any
  export const Upgrade: any
  export const Upload: any
  export const User: any
  export const UserAdd: any
  export const UserAdmin: any
  export const UserExpert: any
  export const UserFemale: any
  export const UserManager: any
  export const UserNew: any
  export const UserPolice: any
  export const UserSettings: any
  export const UserWorker: any
  export const Validate: any
  export const Vend: any
  export const Video: any
  export const View: any
  export const Vimeo: any
  export const VirtualMachine: any
  export const VirtualStorage: any
  export const Visa: any
  export const VmMaintenance: any
  export const Vmware: any
  export const Volume: any
  export const VolumeControl: any
  export const VolumeLow: any
  export const VolumeMute: any
  export const Vulnerability: any
  export const Waypoint: any
  export const Wheelchair: any
  export const WheelchairActive: any
  export const Wifi: any
  export const WifiLow: any
  export const WifiMedium: any
  export const WifiNone: any
  export const Windows: any
  export const WindowsLegacy: any
  export const Wordpress: any
  export const Workshop: any
  export const Yoga: any
  export const Youtube: any
  export const ZoomIn: any
  export const ZoomOut: any
  export const base: any
  export const defaultProps: any
  export const extendDefaultTheme: any
}
