export { ReactComponent as Figma } from './figma.svg'
export { ReactComponent as CreativeCloud } from './creative-cloud.svg'
export { ReactComponent as Illustrator } from './illustrator.svg'
export { ReactComponent as Indesign } from './indesign.svg'
export { ReactComponent as Photoshop } from './photoshop.svg'

export { ReactComponent as Emotion } from './emotion.svg'
export { ReactComponent as Gatsby } from './gatsby.svg'
export { ReactComponent as Graphql } from './graphql.svg'
export { ReactComponent as Javascript } from './javascript.svg'
export { ReactComponent as Jest } from './jest.svg'
export { ReactComponent as React } from './react.svg'
export { ReactComponent as Typescript } from './typescript.svg'
export { ReactComponent as Webpack } from './webpack.svg'

export { ReactComponent as Aws } from './aws.svg'
export { ReactComponent as Docker } from './docker.svg'
export { ReactComponent as Netlify } from './netlify.svg'
export { ReactComponent as Node } from './node.svg'
export { ReactComponent as Prisma } from './prisma.svg'
